name: Upload monaco-editor to AWS S3
on:
  push:
    branches:
      - master
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: yarn
      - name: Upload to S3
        env:
          BASE_S3_URI: s3://frontend.ro
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: yarn upload-monaco-editor-s3
          
